---
title: "K-means Clustering with Original Dataset"
author: "Stephanie Cheng"
date: "2025-04-09"
output: pdf_document
---

```{r setup, include=FALSE}
library(dplyr)
library(tidyr)
library(stats)
library(here)
library(ggplot2)

source("UL_helpers.r")

load("dataset_RData_cluster/new_york_city_data.RData")
```

# K-mean without PCA
Scale each variable to have a mean of 0 and a standard deviation of 1
```{r scale data}
scaled_new_york_city_data <- scale(new_york_city_data)
head(scaled_new_york_city_data)
```

Calculate clustering evaluation with Davies Bouldin index & Within-cluster sum of squares.
See the affect when K is increasing, then we can apply elbow method to avoid 
picking the best k within overfitting case. 
```{r Clustering Metrics}
scaled_new_york_city_data <- as.data.frame(scale(new_york_city_data))

nyc_k_stats_20 <- calculate_k_stats(scaled_new_york_city_data, max_k = 20)
nyc_k_stats_40 <- calculate_k_stats(scaled_new_york_city_data, max_k = 40)

# DBI & WSS plot
elbows_20 <- plot_kmeans(nyc_k_stats_20$errs, nyc_k_stats_20$DBI)
elbows_40 <- plot_kmeans(nyc_k_stats_40$errs, nyc_k_stats_40$DBI)
```

