---
title: "K-means"
author: "Stephanie Cheng"
date: "2025-04-09"
output: pdf_document
---

```{r setup, include=FALSE}
library(dplyr)
library(tidyr)
library(stats)
library(mda)
library(here)
library(ggplot2)
library(gridExtra)
library(reshape2)

load("manhattan_data.RData")
load("bronx_data.RData")
load("brooklyn_data.RData")
load("queens_data.RData")
load("staten_island_data.RData")

source("UL_helpers.r")
```

# Manhattan Result
```{r man_PCA}
manhattan_pca <- pca(manhattan_data, "Manhattan")
```

```{r man_best_K}
manhattan_data_n <- nrow(manhattan_data)
manhattan_max_k <- floor(sqrt(manhattan_data_n / 2))  
manhattan_k_stats <- find_best_k(manhattan_pca, manhattan_max_k)
```

```{r man_KMean_Plot}
plot_kmeans(manhattan_k_stats$errs, manhattan_k_stats$DBI)
```

```{r man_PCs_Comparison}
plot_selected_pcs(manhattan_pca, manhattan_k_stats$best_k,
  pc_pairs = list(c(1, 2), c(1, 3), c(1, 6))
)
show_cluster_legend_plot(manhattan_k_stats$best_k)
```

```{r man_Heatmap}
plot_heatmap_centers(manhattan_pca, manhattan_k_stats$best_k)
```

```{r man_ClusterSummary}
manhattan_cluster_summary <- summarize(
  pca_result = manhattan_pca,
  original_data = manhattan_data,
  best_k = manhattan_k_stats$best_k
)
print(manhattan_cluster_summary)
```

# Bronx Result
```{r Bro_PCA}
bronx_pca <- pca(bronx_data, "Bronx")
```

```{r Bro_best_K}
bronx_data_n <- nrow(bronx_data)
bronx_max_k <- floor(sqrt(bronx_data_n / 2))  
bronx_k_stats <- find_best_k(bronx_pca, bronx_max_k)
```

```{r Bro_KMean_Plot}
plot_kmeans(bronx_k_stats$errs, bronx_k_stats$DBI)
```

```{r Bro_PCs_Comparison}
plot_selected_pcs(bronx_pca, bronx_k_stats$best_k,
  pc_pairs = list(c(1, 2), c(1, 3), c(5,6))
)
show_cluster_legend_plot(bronx_k_stats$best_k)
```

```{r Bro_Heatmap}
plot_heatmap_centers(bronx_pca, bronx_k_stats$best_k)
```

```{r Bro_ClusterSummary}
bronx_cluster_summary <- summarize(
  pca_result = bronx_pca,
  original_data = bronx_data,
  best_k = bronx_k_stats$best_k
)
print(bronx_cluster_summary)
```

# Brooklyn Result

```{r Brook_PCA}
brooklyn_pca <- pca(brooklyn_data, "Brooklyn")
```

```{r Brook_best_K}
brooklyn_data_n <- nrow(brooklyn_data)
brooklyn_max_k <- floor(sqrt(brooklyn_data_n / 2))  
brooklyn_k_stats <- find_best_k(brooklyn_pca, brooklyn_max_k)
```

```{r Brook_KMean_Plot}
plot_kmeans(brooklyn_k_stats$errs, brooklyn_k_stats$DBI)
```

```{r Brook_PCs_Comparison}
plot_selected_pcs(brooklyn_pca, brooklyn_k_stats$best_k,
  pc_pairs = list(c(1, 2), c(1, 3), c(1, 4))
)
show_cluster_legend_plot(brooklyn_k_stats$best_k)
```

```{r Brook_Heatmap}
plot_heatmap_centers(brooklyn_pca, brooklyn_k_stats$best_k)
```

```{r Brook_ClusterSummary}
brooklyn_cluster_summary <- summarize(
  pca_result = brooklyn_pca,
  original_data = brooklyn_data,
  best_k = brooklyn_k_stats$best_k
)
print(brooklyn_cluster_summary)
```

# Queens Result

```{r Queens_PCA}
queens_pca <- pca(queens_data, "Queens")
```

```{r Queens_best_K}
queens_data_n <- nrow(queens_data)
queens_max_k <- floor(sqrt(queens_data_n / 2))  
queens_k_stats <- find_best_k(queens_pca, queens_max_k)
```

```{r Queens_KMean_Plot}
plot_kmeans(queens_k_stats$errs, queens_k_stats$DBI)
```

```{r Queens_PCs_Comparison}
plot_selected_pcs(queens_pca, queens_k_stats$best_k,
  pc_pairs = list(c(1, 2), c(1, 3), c(4, 7))
)
show_cluster_legend_plot(queens_k_stats$best_k)
```

```{r Queens_Heatmap}
plot_heatmap_centers(queens_pca, queens_k_stats$best_k)
```

```{r Queens_ClusterSummary}
queens_cluster_summary <- summarize(
  pca_result = queens_pca,
  original_data = queens_data,
  best_k = queens_k_stats$best_k
)
print(queens_cluster_summary)
```

# Staten Island Result

```{r island_PCA}
staten_island_pca <- pca(staten_island_data, "Staten_Island")
```

```{r island_best_K}
staten_island_data_n <- nrow(staten_island_data)
staten_island_max_k <- floor(sqrt(staten_island_data_n / 2))  
staten_island_k_stats <- find_best_k(staten_island_pca, staten_island_max_k)
```

```{r island_KMean_Plot}
plot_kmeans(staten_island_k_stats$errs, staten_island_k_stats$DBI)
```

```{r island_PCs_Comparison}
plot_selected_pcs(staten_island_pca, staten_island_k_stats$best_k,
  pc_pairs = list(c(1, 2), c(1, 3), c(3, 8))
)
show_cluster_legend_plot(staten_island_k_stats$best_k)
```

```{r island_Heatmap}
plot_heatmap_centers(staten_island_pca, staten_island_k_stats$best_k)
```

```{r island_ClusterSummary}
staten_island_cluster_summary <- summarize(
  pca_result = staten_island_pca,
  original_data = staten_island_data,
  best_k = staten_island_k_stats$best_k
)
print(staten_island_cluster_summary)
```
