---
title: "STAT4601_FINAL_PROJECT"
author: "Trae Smith"
date: "2025-04-03"
output: pdf_document
---

```{r setup, include=FALSE}
library(asbio)
library(DescTools)
library(tidyverse)
library(fastICA)
```


```{r Data_Setup}

##Getting the datasets from the Excel files
manhattan_data<-readxl::read_xlsx(here::here("rollingsales_manhattan.xlsx")) |>janitor::clean_names()
bronx_data<-readxl::read_xlsx(here::here("rollingsales_bronx.xlsx")) |>janitor::clean_names()
brooklyn_data<-readxl::read_xlsx(here::here("rollingsales_brooklyn.xlsx")) |>janitor::clean_names()
queens_data<-readxl::read_xlsx(here::here("rollingsales_queens.xlsx")) |>janitor::clean_names()
staten_island_data<-readxl::read_xlsx(here::here("rollingsales_statenisland.xlsx")) |>janitor::clean_names()

##Column Names are the 4th row
col_names<-make.names(c(manhattan_data[4,]))

##The Information in row 1 to 3 are descriptions of the dataset, and are not needed in the dataframe, the 4th row is the column names and can also be removed

manhattan_data<-manhattan_data[-c(1:4),]
bronx_data<-bronx_data[-c(1:4),]
brooklyn_data<-brooklyn_data[-c(1:4),]
queens_data<-queens_data[-c(1:4),]
staten_island_data<-staten_island_data[-c(1:4),]

##The column names are the same for all data sets, so we can use the same vector for all of them
colnames(manhattan_data)<-col_names
colnames(bronx_data)<-col_names
colnames(brooklyn_data)<-col_names
colnames(queens_data)<-col_names
colnames(staten_island_data)<-col_names


#I have decided to to remove the following columns: Neighborhood, Lot, and Zip code as it is similar to  block causing repetitions, and they can be too unique (causing overfitting). I have also decided to remove Easement as they are all NA, address as they are too specific and unique and would be repetitive to block, apartment number as there would be too many NA and it is not important when it comes to the classification, and sale date as it is not important when it comes to classifying as well and too specific and unique. Likewise, I have decided to remove the missing values and the sale price that is greater than 0. Sale price being 0 is the property being transferred, whether leaglly or by family member. Since it is not being sold, it is not important when it comes to the classification. 

clean_data <- function(data) {
  data %>%
    filter(SALE.PRICE != 0) %>%
    select(
      -NEIGHBORHOOD, -BLOCK, -LOT, -EASEMENT, 
      -ADDRESS, -APARTMENT.NUMBER, -SALE.DATE) %>%
    mutate(
      BOROUGH= as.numeric(BOROUGH), 
      BUILDING.CLASS.CATEGORY= as.numeric(as.factor(BUILDING.CLASS.CATEGORY)), 
      TAX.CLASS.AT.PRESENT= as.numeric(as.factor(TAX.CLASS.AT.PRESENT)), 
      BUILDING.CLASS.AT.PRESENT= as.numeric(
        as.factor(BUILDING.CLASS.AT.PRESENT)), 
      ZIP.CODE= as.numeric(ZIP.CODE), 
      RESIDENTIAL.UNITS= as.numeric(RESIDENTIAL.UNITS), 
      COMMERCIAL.UNITS= as.numeric(COMMERCIAL.UNITS), 
      TOTAL.UNITS= as.numeric(TOTAL.UNITS), 
      LAND.SQUARE.FEET= as.numeric(LAND.SQUARE.FEET), 
      GROSS.SQUARE.FEET= as.numeric(GROSS.SQUARE.FEET), 
      YEAR.BUILT= as.numeric(YEAR.BUILT), 
      TAX.CLASS.AT.TIME.OF.SALE= as.numeric(
        as.factor(TAX.CLASS.AT.TIME.OF.SALE)), 
      BUILDING.CLASS.AT.TIME.OF.SALE= as.numeric(
        as.factor(BUILDING.CLASS.AT.TIME.OF.SALE)),
      SALE.PRICE = as.numeric(SALE.PRICE)
    ) %>%
    na.omit()
}
manhattan_data <- clean_data(manhattan_data)
bronx_data <- clean_data(bronx_data)
brooklyn_data <- clean_data(brooklyn_data)
queens_data <- clean_data(queens_data)
staten_island_data <- clean_data(staten_island_data)

new_york_city_data <- rbind(manhattan_data, bronx_data, brooklyn_data, 
                            queens_data, staten_island_data)
```


```{r PCA}
##PCA for the dataset, specifically for the numericals, along with the standardization
#New_York_City
pca_new_york_city<-prcomp(new_york_city_data, scale.=TRUE)
summary(pca_new_york_city)
apply(pca_new_york_city$rotation, 2, function(x) names(sort(abs(x), decreasing = TRUE)[1]))

#Since Borough is a constant value for each individual borough, we will have to remove it for Principal Component Analysis
#Brooklyn
pca_brooklyn<-prcomp(brooklyn_data[,-c(1)], scale.=TRUE)
summary(pca_brooklyn)
apply(pca_brooklyn$rotation, 2, function(x) names(sort(abs(x), decreasing = TRUE)[1]))

#Manhattan
pca_manhattan<-prcomp(manhattan_data[,-c(1)], scale.=TRUE)
summary(pca_manhattan)
apply(pca_manhattan$rotation, 2, function(x) names(sort(abs(x), decreasing = TRUE)[1]))

#Bronx
pca_bronx<-prcomp(bronx_data[,-c(1)], scale.=TRUE)
summary(pca_bronx)
apply(pca_bronx$rotation, 2, function(x) names(sort(abs(x), decreasing = TRUE)[1]))

#Queens
pca_queens<-prcomp(queens_data[,-c(1)], scale.=TRUE)
summary(pca_queens)
apply(pca_queens$rotation, 2, function(x) names(sort(abs(x), decreasing = TRUE)[1]))

#Staten Island
pca_staten_island<-prcomp(staten_island_data[,-c(1)], scale.=TRUE)
summary(pca_staten_island)
apply(pca_staten_island$rotation, 2, function(x) names(sort(abs(x), decreasing = TRUE)[1]))

```



```{r ICA}
set.seed(1234)
#we can also use ICA to find the independent components of the dataset
ICA_nyc<-fastICA(new_york_city_data, n.comp =8)
ICA_brooklyn<-fastICA(brooklyn_data, n.comp =7)
ICA_manhattan<-fastICA(manhattan_data, n.comp =6)
ICA_bronx<-fastICA(bronx_data, n.comp =6)
ICA_queens<-fastICA(queens_data, n.comp =7)
ICA_staten_island<-fastICA(staten_island_data, n.comp =7)


```
Since all of the correlation of prinicpal components are close to 0, we can say that they are independent. 



```{r Save_Datasets}

save(manhattan_data, file = "manhattan_data.RData")
save(bronx_data, file = "bronx_data.RData")
save(brooklyn_data, file = "brooklyn_data.RData")
save(queens_data, file = "queens_data.RData")
save(staten_island_data, file = "staten_island_data.RData")
save(new_york_city_data, file = "new_york_city_data.RData")

##PCA Data
save(pca_new_york_city, file = "pca_new_york_city.RData")
save(pca_brooklyn, file = "pca_brooklyn.RData")
save(pca_manhattan, file = "pca_manhattan.RData")
save(pca_bronx, file = "pca_bronx.RData")
save(pca_queens, file = "pca_queens.RData")
save(pca_staten_island, file = "pca_staten_island.RData")


#ICA Data
save(ICA_nyc, file = "ICA_nyc.RData")
save(ICA_brooklyn, file = "ICA_brooklyn.RData")
save(ICA_manhattan, file = "ICA_manhattan.RData")
save(ICA_bronx, file = "ICA_bronx.RData")
save(ICA_queens, file = "ICA_queens.RData")
save(ICA_staten_island, file = "ICA_staten_island.RData")

```
